# Automated Setup Script for Global Liquidity Dashboard (PowerShell)
# Run this script to set up your secrets.toml file

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Global Liquidity Dashboard Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Create .streamlit directory
Write-Host "Creating .streamlit directory..." -ForegroundColor Yellow
$StreamlitPath = "$env:USERPROFILE\.streamlit"
New-Item -ItemType Directory -Path $StreamlitPath -Force | Out-Null

if (Test-Path $StreamlitPath) {
    Write-Host "[OK] Directory created/exists: $StreamlitPath" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Could not create directory" -ForegroundColor Red
    pause
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Enter Your FRED API Key" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Get your free API key from:" -ForegroundColor White
Write-Host "https://fred.stlouisfed.org/docs/api/api_key.html" -ForegroundColor Blue
Write-Host ""

$FredKey = Read-Host "Paste your FRED API key here"

if ([string]::IsNullOrWhiteSpace($FredKey)) {
    Write-Host "[ERROR] No API key entered!" -ForegroundColor Red
    pause
    exit 1
}

# Create secrets.toml
Write-Host ""
Write-Host "Creating secrets.toml file..." -ForegroundColor Yellow

$SecretsContent = @"
# Streamlit Secrets Configuration
# Auto-generated by setup script

FRED_API_KEY = "$FredKey"
"@

$SecretsPath = "$StreamlitPath\secrets.toml"
$SecretsContent | Out-File -FilePath $SecretsPath -Encoding utf8

if (Test-Path $SecretsPath) {
    Write-Host "[OK] secrets.toml created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "File location:" -ForegroundColor White
    Write-Host $SecretsPath -ForegroundColor Yellow
    Write-Host ""
} else {
    Write-Host "[ERROR] Failed to create secrets.toml" -ForegroundColor Red
    pause
    exit 1
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Testing Your Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Installing/upgrading required packages..." -ForegroundColor Yellow

pip install --upgrade streamlit pandas plotly fredapi numpy requests

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "You can now run the dashboard with:" -ForegroundColor White
Write-Host "    streamlit run global_liquidity_dashboard_v2.py" -ForegroundColor Yellow
Write-Host ""

$Response = Read-Host "Would you like to start the dashboard now? (Y/N)"

if ($Response -eq "Y" -or $Response -eq "y") {
    Write-Host ""
    Write-Host "Starting dashboard..." -ForegroundColor Yellow
    streamlit run global_liquidity_dashboard_v2.py
} else {
    Write-Host ""
    Write-Host "Setup complete! Run the dashboard anytime with:" -ForegroundColor White
    Write-Host "    streamlit run global_liquidity_dashboard_v2.py" -ForegroundColor Yellow
    Write-Host ""
}